In [1]:
import numpy as np

In [4]:
matriz = np.arange(9).reshape(3, 3)

In [5]:
print(matriz)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
matriz_identidad = np.identity(6)

In [7]:
print(matriz_identidad)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
